//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for ActualizarImagenesClienteRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActualizarImagenesClienteRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cabeceraEntrada" type="{http://xmlns.bancocajasocial.com/co/comunes/schema/Cabeceras/V1.0}CabeceraEntrada" minOccurs="0"/&gt;
 *         &lt;element name="numIdentificacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="canalLlamando" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImagenRut" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImagenDocumentoID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImagenDocumentoIDRev" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImagenRegistroCliente" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImagenFotoCliente" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idPromotor" type="{http://xmlns.bancocajasocial.com/co/schemas/operacion/sam/infoPersona/v1.0}IdentificacionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActualizarImagenesClienteRequestType", propOrder = {
    "cabeceraEntrada",
    "numIdentificacion",
    "tipoDocumento",
    "canalLlamando",
    "imagenRut",
    "imagenDocumentoID",
    "imagenDocumentoIDRev",
    "imagenRegistroCliente",
    "imagenFotoCliente",
    "idPromotor"
})
@Getter
@Setter
@NoArgsConstructor 
 public class ActualizarImagenesClienteRequestType {

    protected CabeceraEntrada cabeceraEntrada;
    @XmlElement(required = true)
    protected String numIdentificacion;
    @XmlElement(required = true)
    protected String tipoDocumento;
    @XmlElement(required = true)
    protected String canalLlamando;
    @XmlElement(name = "ImagenRut", required = true)
    protected String imagenRut;
    @XmlElement(name = "ImagenDocumentoID", required = true)
    protected String imagenDocumentoID;
    @XmlElement(name = "ImagenDocumentoIDRev", required = true)
    protected String imagenDocumentoIDRev;
    @XmlElement(name = "ImagenRegistroCliente", required = true)
    protected String imagenRegistroCliente;
    @XmlElement(name = "ImagenFotoCliente", required = true)
    protected String imagenFotoCliente;
    protected IdentificacionType idPromotor;

}
