//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for DatosPaginacionEntType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosPaginacionEntType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="registroInicial" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="registrosPorPag" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="rangoFecha" type="{http://xmlns.bancocajasocial.com/co/schemas/sam/cliente/infoPaginacion/v1.0}RangofechasType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosPaginacionEntType", namespace = "http://xmlns.bancocajasocial.com/co/schemas/sam/cliente/infoPaginacion/v1.0", propOrder = {
    "registroInicial",
    "registrosPorPag",
    "rangoFecha"
})
@Getter
@Setter
@NoArgsConstructor 
 public class DatosPaginacionEntType {

    @XmlElement(required = true)
    protected BigInteger registroInicial;
    @XmlElement(required = true)
    protected BigInteger registrosPorPag;
    @XmlElement(required = true)
    protected RangofechasType rangoFecha;
}
