//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for InfoProductoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoProductoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numProducto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaApertura" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="valorPrestamo" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="saldoAFecha" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="numeroCuotas" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="cuotasPagadas" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="fechaVencimiento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="estadoCredito" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoProductoType", propOrder = {
    "numProducto",
    "fechaApertura",
    "valorPrestamo",
    "saldoAFecha",
    "numeroCuotas",
    "cuotasPagadas",
    "fechaVencimiento",
    "estadoCredito"
})
@Getter
@Setter
@NoArgsConstructor 
 public class InfoProductoType {

    @XmlElement(required = true)
    protected String numProducto;
    @XmlElement(required = true)
    protected String fechaApertura;
    @XmlElement(required = true)
    protected BigDecimal valorPrestamo;
    @XmlElement(required = true)
    protected BigDecimal saldoAFecha;
    protected int numeroCuotas;
    protected int cuotasPagadas;
    @XmlElement(required = true)
    protected String fechaVencimiento;
    protected int estadoCredito;

}
