//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for InfoPagoCredito complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoPagoCredito"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numAlcacia" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="valorPagar" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="flagTipoPago" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoPagoCredito", propOrder = {
    "numAlcacia",
    "valorPagar",
    "flagTipoPago"
})
@Getter
@Setter
@NoArgsConstructor 
 public class InfoPagoCredito {

    @XmlElement(required = true)
    protected BigInteger numAlcacia;
    @XmlElement(required = true)
    protected BigDecimal valorPagar;
    @XmlElement(required = true)
    protected BigInteger flagTipoPago;
}
