//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for InfoDebitoAutomaticoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoDebitoAutomaticoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="celular" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numCredito" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numAlcancia" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="indicadorDebAuto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoDebitoAutomaticoType", propOrder = {
    "celular",
    "numCredito",
    "numAlcancia",
    "indicadorDebAuto"
})
@Getter
@Setter
@NoArgsConstructor 
 public class InfoDebitoAutomaticoType {

    @XmlElement(required = true)
    protected String celular;
    @XmlElement(required = true)
    protected String numCredito;
    @XmlElement(required = true)
    protected BigInteger numAlcancia;
    @XmlElement(required = true)
    protected String indicadorDebAuto;
}
