//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for InfoUbicacionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoUbicacionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dirRecidencia" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="barrio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ciudad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="telefonoUno" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="telefonoDos" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="celularUno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="celularDos" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoVivienda" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoUbicacionType", namespace = "http://xmlns.bancocajasocial.com/co/schemas/operacion/sam/infoPersona/v1.0", propOrder = {
    "dirRecidencia",
    "barrio",
    "ciudad",
    "telefonoUno",
    "telefonoDos",
    "celularUno",
    "celularDos",
    "tipoVivienda"
})
@Getter
@Setter
@NoArgsConstructor 
 public class InfoUbicacionType {

    @XmlElement(required = true)
    protected String dirRecidencia;
    @XmlElement(required = true)
    protected String barrio;
    @XmlElement(required = true)
    protected String ciudad;
    @XmlElement(required = true)
    protected BigInteger telefonoUno;
    @XmlElement(required = true)
    protected BigInteger telefonoDos;
    @XmlElement(required = true)
    protected String celularUno;
    @XmlElement(required = true)
    protected String celularDos;
    @XmlElement(required = true)
    protected String tipoVivienda;
}
