//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for InfoPersonaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoPersonaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fchNacimiento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="genero" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fchExpedicion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="correoElectronico" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="GrupoSanguineo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="numeroCelular" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Ocupacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mesesOcupacion" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="aniosOcupacion" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="nivelEducativo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="personasACargo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoPersonaType", namespace = "http://xmlns.bancocajasocial.com/co/schemas/operacion/sam/infoPersona/v1.0", propOrder = {
    "fchNacimiento",
    "genero",
    "fchExpedicion",
    "correoElectronico",
    "grupoSanguineo",
    "numeroCelular",
    "ocupacion",
    "mesesOcupacion",
    "aniosOcupacion",
    "nivelEducativo",
    "personasACargo"
})
@Getter
@Setter
@NoArgsConstructor 
 public class InfoPersonaType {

    @XmlElement(required = true)
    protected String fchNacimiento;
    @XmlElement(required = true)
    protected String genero;
    @XmlElement(required = true)
    protected String fchExpedicion;
    @XmlElement(required = true)
    protected String correoElectronico;
    @XmlElement(name = "GrupoSanguineo")
    protected String grupoSanguineo;
    @XmlElement(required = true)
    protected String numeroCelular;
    @XmlElement(name = "Ocupacion")
    protected String ocupacion;
    protected BigInteger mesesOcupacion;
    protected BigInteger aniosOcupacion;
    protected String nivelEducativo;
    protected BigInteger personasACargo;
}
