//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//

package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the co.com.bcs.apibanco.services.client.sam
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
@NoArgsConstructor
 public class ObjectFactory {

    private static final String QNAME_SAM_CLIENTE = "http://xmlns.bancocajasocial.com/co/schemas/sam/cliente/servicioSAMCliente/v1.0";
    private static final String QNAME_CABECERA = "http://xmlns.bancocajasocial.com/co/comunes/schema/Cabeceras/V1.0";
    private static final String QNAME_INFO_PERSONA = "http://xmlns.bancocajasocial.com/co/schemas/operacion/sam/infoPersona/v1.0";

    private static final QName _AutenticarClienteRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "autenticarClienteRequest");
    private static final QName _AutenticarClienteResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "autenticarClienteResponse");
    private static final QName _CambiarClaveRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "cambiarClaveRequest");
    private static final QName _CambiarClaveResponse_QNAME = new QName(QNAME_SAM_CLIENTE, "cambiarClaveResponse");
    private static final QName _ConsultarComprobantePagoRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarComprobantePagoRequest");
    private static final QName _ConsultarComprobantePagoResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarComprobantePagoResponse");
    private static final QName _HabilitarDebitoAutomaticoRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "habilitarDebitoAutomaticoRequest");
    private static final QName _HabilitarDebitoAutomaticoResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "habilitarDebitoAutomaticoResponse");
    private static final QName _ConsultarHistoricoPagosRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarHistoricoPagosRequest");
    private static final QName _ConsultarHistoricoPagosResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarHistoricoPagosResponse");
    private static final QName _AceptarCreditoRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "aceptarCreditoRequest");
    private static final QName _AceptarCreditoResponse_QNAME = new QName(QNAME_SAM_CLIENTE, "aceptarCreditoResponse");
    private static final QName _ConsultarEstadoCreditoRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarEstadoCreditoRequest");
    private static final QName _ConsultarEstadoCreditoResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarEstadoCreditoResponse");
    private static final QName _ConsultarEstadoSolicitudRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarEstadoSolicitudRequest");
    private static final QName _ConsultarEstadoSolicitudResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarEstadoSolicitudResponse");
    private static final QName _SolicitarCreditoRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "solicitarCreditoRequest");
    private static final QName _SolicitarCreditoResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "solicitarCreditoResponse");
    private static final QName _PagarCreditoResponse_QNAME = new QName(QNAME_SAM_CLIENTE, "pagarCreditoResponse");
    private static final QName _PagarCreditoRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "pagarCreditoRequest");
    private static final QName _CalificarPromotorRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "calificarPromotorRequest");
    private static final QName _CalificarPromotorResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "calificarPromotorResponse");
    private static final QName _ConsultarPromotorRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarPromotorRequest");
    private static final QName _ConsultarPromotorResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarPromotorResponse");
    private static final QName _RescateRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "rescateRequest");
    private static final QName _RealizarRescateResponse_QNAME = new QName(QNAME_SAM_CLIENTE, "realizarRescateResponse");
    private static final QName _SolicitarRescateResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "solicitarRescateResponse");
    private static final QName _UltimosMovimientosRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "ultimosMovimientosRequest");
    private static final QName _UltimosMovimientosResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "ultimosMovimientosResponse");
    private static final QName _ConsultarMovimientosAlcanciaRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarMovimientosAlcanciaRequest");
    private static final QName _ConsultarMovimientosAlcanciaResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarMovimientosAlcanciaResponse");
    private static final QName _ConsultarProductosClienteRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarProductosClienteRequest");
    private static final QName _ConsultarProductosClienteResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarProductosClienteResponse");
    private static final QName _RegistrarClienteRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "registrarClienteRequest");
    private static final QName _RegistrarClienteResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "registrarClienteResponse");
    private static final QName _ActualizarRegistroClienteRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "actualizarRegistroClienteRequest");
    private static final QName _ActualizarRegistroClienteResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "actualizarRegistroClienteResponse");
    private static final QName _FinalizarRegistroClienteRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "finalizarRegistroClienteRequest");
    private static final QName _FinalizarRegistroClienteResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "finalizarRegistroClienteResponse");
    private static final QName _ConsultarRetirosDisponiblesRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarRetirosDisponiblesRequest");
    private static final QName _ConsultarRetirosDisponiblesResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "consultarRetirosDisponiblesResponse");
    private static final QName _ValidacionesVariasRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "validacionesVariasRequest");
    private static final QName _ValidacionesVariasResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "validacionesVariasResponse");
    private static final QName _ValidarAlcanciaRequest_QNAME = new QName(QNAME_SAM_CLIENTE, "validarAlcanciaRequest");
    private static final QName _ValidarAlcanciaResponse_QNAME = new QName(QNAME_SAM_CLIENTE, "validarAlcanciaResponse");
    private static final QName _ActualizarImagenesRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "actualizarImagenesRequest");
    private static final QName _ActualizarImagenesResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "actualizarImagenesResponse");
    private static final QName _FinSolicitudCreditoRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "finSolicitudCreditoRequest");
    private static final QName _FinSolicitudCreditoResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "finSolicitudCreditoResponse");
    private static final QName _ActualizarImagenesClienteRequest_QNAME = new QName(QNAME_SAM_CLIENTE,
            "actualizarImagenesClienteRequest");
    private static final QName _ActualizarImagenesClienteResponse_QNAME = new QName(QNAME_SAM_CLIENTE,
            "actualizarImagenesClienteResponse");
    private static final QName _CabeceraSalida_QNAME = new QName(QNAME_CABECERA, "cabeceraSalida");
    private static final QName _CabeceraEntrada_QNAME = new QName(QNAME_CABECERA, "cabeceraEntrada");
    private static final QName _CabeceraRespuestaMultiple_QNAME = new QName(QNAME_CABECERA,
            "cabeceraRespuestaMultiple");
    private static final QName _InfoPersona_QNAME = new QName(QNAME_INFO_PERSONA, "infoPersona");
    private static final QName _InfoUbicacion_QNAME = new QName(QNAME_INFO_PERSONA, "infoUbicacion");
    private static final QName _InfoPersonal_QNAME = new QName(QNAME_INFO_PERSONA, "infoPersonal");
    private static final QName _InfoConyuge_QNAME = new QName(QNAME_INFO_PERSONA, "infoConyuge");
    private static final QName _InfoActividadEconomica_QNAME = new QName(QNAME_INFO_PERSONA, "infoActividadEconomica");
    private static final QName _InfoIngresos_QNAME = new QName(QNAME_INFO_PERSONA, "infoIngresos");
    private static final QName _InfoFamiliar_QNAME = new QName(QNAME_INFO_PERSONA, "infoFamiliar");
    private static final QName _InfoSegSocial_QNAME = new QName(QNAME_INFO_PERSONA, "infoSegSocial");
    private static final QName _NombreCompleto_QNAME = new QName(QNAME_INFO_PERSONA, "nombreCompleto");
    private static final QName _ProductoComun_QNAME = new QName(QNAME_INFO_PERSONA, "productoComun");

    /**
     * Create an instance of {@link AutenticarClienteRequestType }
     * 
     */
    public AutenticarClienteRequestType createAutenticarClienteRequestType() {
        return new AutenticarClienteRequestType();
    }

    /**
     * Create an instance of {@link AutenticarClienteResponseType }
     * 
     */
    public AutenticarClienteResponseType createAutenticarClienteResponseType() {
        return new AutenticarClienteResponseType();
    }

    /**
     * Create an instance of {@link CambiarClaveRequestType }
     * 
     */
    public CambiarClaveRequestType createCambiarClaveRequestType() {
        return new CambiarClaveRequestType();
    }

    /**
     * Create an instance of {@link CambiarClaveResponseType }
     * 
     */
    public CambiarClaveResponseType createCambiarClaveResponseType() {
        return new CambiarClaveResponseType();
    }

    /**
     * Create an instance of {@link ConsultarComprobantePagoRequestType }
     * 
     */
    public ConsultarComprobantePagoRequestType createConsultarComprobantePagoRequestType() {
        return new ConsultarComprobantePagoRequestType();
    }

    /**
     * Create an instance of {@link ConsultarComprobantePagoResponseType }
     * 
     */
    public ConsultarComprobantePagoResponseType createConsultarComprobantePagoResponseType() {
        return new ConsultarComprobantePagoResponseType();
    }

    /**
     * Create an instance of {@link HabilitarDebitoAutomaticoRequestType }
     * 
     */
    public HabilitarDebitoAutomaticoRequestType createHabilitarDebitoAutomaticoRequestType() {
        return new HabilitarDebitoAutomaticoRequestType();
    }

    /**
     * Create an instance of {@link HabilitarDebitoAutomaticoResponseType }
     * 
     */
    public HabilitarDebitoAutomaticoResponseType createHabilitarDebitoAutomaticoResponseType() {
        return new HabilitarDebitoAutomaticoResponseType();
    }

    /**
     * Create an instance of {@link ConsultarHistoricoPagosRequestType }
     * 
     */
    public ConsultarHistoricoPagosRequestType createConsultarHistoricoPagosRequestType() {
        return new ConsultarHistoricoPagosRequestType();
    }

    /**
     * Create an instance of {@link ConsultarHistoricoPagosResponseType }
     * 
     */
    public ConsultarHistoricoPagosResponseType createConsultarHistoricoPagosResponseType() {
        return new ConsultarHistoricoPagosResponseType();
    }

    /**
     * Create an instance of {@link AceptarCreditoRequestType }
     * 
     */
    public AceptarCreditoRequestType createAceptarCreditoRequestType() {
        return new AceptarCreditoRequestType();
    }

    /**
     * Create an instance of {@link AceptarCreditoResponseType }
     * 
     */
    public AceptarCreditoResponseType createAceptarCreditoResponseType() {
        return new AceptarCreditoResponseType();
    }

    /**
     * Create an instance of {@link ConsultarEstadoCreditoRequestType }
     * 
     */
    public ConsultarEstadoCreditoRequestType createConsultarEstadoCreditoRequestType() {
        return new ConsultarEstadoCreditoRequestType();
    }

    /**
     * Create an instance of {@link ConsultarEstadoCreditoResponseType }
     * 
     */
    public ConsultarEstadoCreditoResponseType createConsultarEstadoCreditoResponseType() {
        return new ConsultarEstadoCreditoResponseType();
    }

    /**
     * Create an instance of {@link ConsultarEstadoSolicitudRequestType }
     * 
     */
    public ConsultarEstadoSolicitudRequestType createConsultarEstadoSolicitudRequestType() {
        return new ConsultarEstadoSolicitudRequestType();
    }

    /**
     * Create an instance of {@link ConsultarEstadoSolicitudResponseType }
     * 
     */
    public ConsultarEstadoSolicitudResponseType createConsultarEstadoSolicitudResponseType() {
        return new ConsultarEstadoSolicitudResponseType();
    }

    /**
     * Create an instance of {@link SolicitudCreditoRequestType }
     * 
     */
    public SolicitudCreditoRequestType createSolicitudCreditoRequestType() {
        return new SolicitudCreditoRequestType();
    }

    /**
     * Create an instance of {@link SolicitudCreditoResponseType }
     * 
     */
    public SolicitudCreditoResponseType createSolicitudCreditoResponseType() {
        return new SolicitudCreditoResponseType();
    }

    /**
     * Create an instance of {@link PagarCreditoResponseType }
     * 
     */
    public PagarCreditoResponseType createPagarCreditoResponseType() {
        return new PagarCreditoResponseType();
    }

    /**
     * Create an instance of {@link PagarCreditoRequestType }
     * 
     */
    public PagarCreditoRequestType createPagarCreditoRequestType() {
        return new PagarCreditoRequestType();
    }

    /**
     * Create an instance of {@link CalificarPromotorRequestType }
     * 
     */
    public CalificarPromotorRequestType createCalificarPromotorRequestType() {
        return new CalificarPromotorRequestType();
    }

    /**
     * Create an instance of {@link CalificarPromotorResponseType }
     * 
     */
    public CalificarPromotorResponseType createCalificarPromotorResponseType() {
        return new CalificarPromotorResponseType();
    }

    /**
     * Create an instance of {@link ConsultarPromotorRequestType }
     * 
     */
    public ConsultarPromotorRequestType createConsultarPromotorRequestType() {
        return new ConsultarPromotorRequestType();
    }

    /**
     * Create an instance of {@link ConsultarPromotorResponseType }
     * 
     */
    public ConsultarPromotorResponseType createConsultarPromotorResponseType() {
        return new ConsultarPromotorResponseType();
    }

    /**
     * Create an instance of {@link RescateRequestType }
     * 
     */
    public RescateRequestType createRescateRequestType() {
        return new RescateRequestType();
    }

    /**
     * Create an instance of {@link RealizarRescateResponseType }
     * 
     */
    public RealizarRescateResponseType createRealizarRescateResponseType() {
        return new RealizarRescateResponseType();
    }

    /**
     * Create an instance of {@link SolicitarRescateResponseType }
     * 
     */
    public SolicitarRescateResponseType createSolicitarRescateResponseType() {
        return new SolicitarRescateResponseType();
    }

    /**
     * Create an instance of {@link UltimosMovimientosRequestType }
     * 
     */
    public UltimosMovimientosRequestType createUltimosMovimientosRequestType() {
        return new UltimosMovimientosRequestType();
    }

    /**
     * Create an instance of {@link UltimosMovimientosResponseType }
     * 
     */
    public UltimosMovimientosResponseType createUltimosMovimientosResponseType() {
        return new UltimosMovimientosResponseType();
    }

    /**
     * Create an instance of {@link ConsultarMovimientosAlcanciaRequestType }
     * 
     */
    public ConsultarMovimientosAlcanciaRequestType createConsultarMovimientosAlcanciaRequestType() {
        return new ConsultarMovimientosAlcanciaRequestType();
    }

    /**
     * Create an instance of {@link ConsultarMovimientosAlcanciaResponseType }
     * 
     */
    public ConsultarMovimientosAlcanciaResponseType createConsultarMovimientosAlcanciaResponseType() {
        return new ConsultarMovimientosAlcanciaResponseType();
    }

    /**
     * Create an instance of {@link ConsultarProductosClienteRequestType }
     * 
     */
    public ConsultarProductosClienteRequestType createConsultarProductosClienteRequestType() {
        return new ConsultarProductosClienteRequestType();
    }

    /**
     * Create an instance of {@link ConsultarProductosClienteResponseType }
     * 
     */
    public ConsultarProductosClienteResponseType createConsultarProductosClienteResponseType() {
        return new ConsultarProductosClienteResponseType();
    }

    /**
     * Create an instance of {@link RegistroClienteRequestType }
     * 
     */
    public RegistroClienteRequestType createRegistroClienteRequestType() {
        return new RegistroClienteRequestType();
    }

    /**
     * Create an instance of {@link RegistroClienteResponseType }
     * 
     */
    public RegistroClienteResponseType createRegistroClienteResponseType() {
        return new RegistroClienteResponseType();
    }

    /**
     * Create an instance of {@link ActualizarRegistroClienteRequestType }
     * 
     */
    public ActualizarRegistroClienteRequestType createActualizarRegistroClienteRequestType() {
        return new ActualizarRegistroClienteRequestType();
    }

    /**
     * Create an instance of {@link ActualizarRegistroClienteResponseType }
     * 
     */
    public ActualizarRegistroClienteResponseType createActualizarRegistroClienteResponseType() {
        return new ActualizarRegistroClienteResponseType();
    }

    /**
     * Create an instance of {@link FinalizarRegistroClienteRequestType }
     * 
     */
    public FinalizarRegistroClienteRequestType createFinalizarRegistroClienteRequestType() {
        return new FinalizarRegistroClienteRequestType();
    }

    /**
     * Create an instance of {@link FinalizarRegistroClienteResponseType }
     * 
     */
    public FinalizarRegistroClienteResponseType createFinalizarRegistroClienteResponseType() {
        return new FinalizarRegistroClienteResponseType();
    }

    /**
     * Create an instance of {@link ConsultarRetirosDisponiblesRequestType }
     * 
     */
    public ConsultarRetirosDisponiblesRequestType createConsultarRetirosDisponiblesRequestType() {
        return new ConsultarRetirosDisponiblesRequestType();
    }

    /**
     * Create an instance of {@link ConsultarRetirosDisponiblesResponseType }
     * 
     */
    public ConsultarRetirosDisponiblesResponseType createConsultarRetirosDisponiblesResponseType() {
        return new ConsultarRetirosDisponiblesResponseType();
    }

    /**
     * Create an instance of {@link ValidacionesVariasRequestType }
     * 
     */
    public ValidacionesVariasRequestType createValidacionesVariasRequestType() {
        return new ValidacionesVariasRequestType();
    }

    /**
     * Create an instance of {@link ValidacionesVariasResponseType }
     * 
     */
    public ValidacionesVariasResponseType createValidacionesVariasResponseType() {
        return new ValidacionesVariasResponseType();
    }

    /**
     * Create an instance of {@link ValidarAlcanciaRequestType }
     * 
     */
    public ValidarAlcanciaRequestType createValidarAlcanciaRequestType() {
        return new ValidarAlcanciaRequestType();
    }

    /**
     * Create an instance of {@link ValidarAlcanciaResponseType }
     * 
     */
    public ValidarAlcanciaResponseType createValidarAlcanciaResponseType() {
        return new ValidarAlcanciaResponseType();
    }

    /**
     * Create an instance of {@link ActualizarImagenesRequestType }
     * 
     */
    public ActualizarImagenesRequestType createActualizarImagenesRequestType() {
        return new ActualizarImagenesRequestType();
    }

    /**
     * Create an instance of {@link ActualizarImagenesResponseType }
     * 
     */
    public ActualizarImagenesResponseType createActualizarImagenesResponseType() {
        return new ActualizarImagenesResponseType();
    }

    /**
     * Create an instance of {@link FinSolicitudCreditoRequestType }
     * 
     */
    public FinSolicitudCreditoRequestType createFinSolicitudCreditoRequestType() {
        return new FinSolicitudCreditoRequestType();
    }

    /**
     * Create an instance of {@link FinSolicitudCreditoResponseType }
     * 
     */
    public FinSolicitudCreditoResponseType createFinSolicitudCreditoResponseType() {
        return new FinSolicitudCreditoResponseType();
    }

    /**
     * Create an instance of {@link ActualizarImagenesClienteRequestType }
     * 
     */
    public ActualizarImagenesClienteRequestType createActualizarImagenesClienteRequestType() {
        return new ActualizarImagenesClienteRequestType();
    }

    /**
     * Create an instance of {@link ActualizarImagenesClienteResponseType }
     * 
     */
    public ActualizarImagenesClienteResponseType createActualizarImagenesClienteResponseType() {
        return new ActualizarImagenesClienteResponseType();
    }

    /**
     * Create an instance of {@link InfoDebitoAutomaticoType }
     * 
     */
    public InfoDebitoAutomaticoType createInfoDebitoAutomaticoType() {
        return new InfoDebitoAutomaticoType();
    }

    /**
     * Create an instance of {@link InfoHistoricoPagosType }
     * 
     */
    public InfoHistoricoPagosType createInfoHistoricoPagosType() {
        return new InfoHistoricoPagosType();
    }

    /**
     * Create an instance of {@link ListaSalHistoPagos }
     * 
     */
    public ListaSalHistoPagos createListaSalHistoPagos() {
        return new ListaSalHistoPagos();
    }

    /**
     * Create an instance of {@link HistoricoPagosType }
     * 
     */
    public HistoricoPagosType createHistoricoPagosType() {
        return new HistoricoPagosType();
    }

    /**
     * Create an instance of {@link EstadoSolicitudType }
     * 
     */
    public EstadoSolicitudType createEstadoSolicitudType() {
        return new EstadoSolicitudType();
    }

    /**
     * Create an instance of {@link DataAceptaCreditoType }
     * 
     */
    public DataAceptaCreditoType createDataAceptaCreditoType() {
        return new DataAceptaCreditoType();
    }

    /**
     * Create an instance of {@link InfoSoliCreditoType }
     * 
     */
    public InfoSoliCreditoType createInfoSoliCreditoType() {
        return new InfoSoliCreditoType();
    }

    /**
     * Create an instance of {@link InfoPagoCredito }
     * 
     */
    public InfoPagoCredito createInfoPagoCredito() {
        return new InfoPagoCredito();
    }

    /**
     * Create an instance of {@link PromotorDataType }
     * 
     */
    public PromotorDataType createPromotorDataType() {
        return new PromotorDataType();
    }

    /**
     * Create an instance of {@link ListaPromotorDataType }
     * 
     */
    public ListaPromotorDataType createListaPromotorDataType() {
        return new ListaPromotorDataType();
    }

    /**
     * Create an instance of {@link ListaMovimientosType }
     * 
     */
    public ListaMovimientosType createListaMovimientosType() {
        return new ListaMovimientosType();
    }

    /**
     * Create an instance of {@link InfoMovimientoType }
     * 
     */
    public InfoMovimientoType createInfoMovimientoType() {
        return new InfoMovimientoType();
    }

    /**
     * Create an instance of {@link ListaProductosType }
     * 
     */
    public ListaProductosType createListaProductosType() {
        return new ListaProductosType();
    }

    /**
     * Create an instance of {@link InfoProductoType }
     * 
     */
    public InfoProductoType createInfoProductoType() {
        return new InfoProductoType();
    }

    /**
     * Create an instance of {@link EstadoValidacionType }
     * 
     */
    public EstadoValidacionType createEstadoValidacionType() {
        return new EstadoValidacionType();
    }

    /**
     * Create an instance of {@link ValidaDocumentosType }
     * 
     */
    public ValidaDocumentosType createValidaDocumentosType() {
        return new ValidaDocumentosType();
    }

    /**
     * Create an instance of {@link DatosPaginacionEntType }
     * 
     */
    public DatosPaginacionEntType createDatosPaginacionEntType() {
        return new DatosPaginacionEntType();
    }

    /**
     * Create an instance of {@link RangofechasType }
     * 
     */
    public RangofechasType createRangofechasType() {
        return new RangofechasType();
    }

    /**
     * Create an instance of {@link DatosPaginacionSalType }
     * 
     */
    public DatosPaginacionSalType createDatosPaginacionSalType() {
        return new DatosPaginacionSalType();
    }

    /**
     * Create an instance of {@link ClienteGananciaType }
     * 
     */
    public ClienteGananciaType createClienteGananciaType() {
        return new ClienteGananciaType();
    }

    /**
     * Create an instance of {@link DetalleCuotasPagoType }
     * 
     */
    public DetalleCuotasPagoType createDetalleCuotasPagoType() {
        return new DetalleCuotasPagoType();
    }

    /**
     * Create an instance of {@link CabeceraSalida }
     * 
     */
    public CabeceraSalida createCabeceraSalida() {
        return new CabeceraSalida();
    }

    /**
     * Create an instance of {@link CabeceraEntrada }
     * 
     */
    public CabeceraEntrada createCabeceraEntrada() {
        return new CabeceraEntrada();
    }

    /**
     * Create an instance of {@link CabeceraRespuestaMultiple }
     * 
     */
    public CabeceraRespuestaMultiple createCabeceraRespuestaMultiple() {
        return new CabeceraRespuestaMultiple();
    }

    /**
     * Create an instance of {@link DetalleError }
     * 
     */
    public DetalleError createDetalleError() {
        return new DetalleError();
    }

    /**
     * Create an instance of {@link Invocador }
     * 
     */
    public Invocador createInvocador() {
        return new Invocador();
    }

    /**
     * Create an instance of {@link RespuestaError }
     * 
     */
    public RespuestaError createRespuestaError() {
        return new RespuestaError();
    }

    /**
     * Create an instance of {@link Seguridad }
     * 
     */
    public Seguridad createSeguridad() {
        return new Seguridad();
    }

    /**
     * Create an instance of {@link DetalleRespuesta }
     * 
     */
    public DetalleRespuesta createDetalleRespuesta() {
        return new DetalleRespuesta();
    }

    /**
     * Create an instance of {@link DetallesRespuestas }
     * 
     */
    public DetallesRespuestas createDetallesRespuestas() {
        return new DetallesRespuestas();
    }

    /**
     * Create an instance of {@link InfoPersonaType }
     * 
     */
    public InfoPersonaType createInfoPersonaType() {
        return new InfoPersonaType();
    }

    /**
     * Create an instance of {@link InfoUbicacionType }
     * 
     */
    public InfoUbicacionType createInfoUbicacionType() {
        return new InfoUbicacionType();
    }

    /**
     * Create an instance of {@link InfoPersonalType }
     * 
     */
    public InfoPersonalType createInfoPersonalType() {
        return new InfoPersonalType();
    }

    /**
     * Create an instance of {@link InfoConyugeType }
     * 
     */
    public InfoConyugeType createInfoConyugeType() {
        return new InfoConyugeType();
    }

    /**
     * Create an instance of {@link InfoActividadEconomicaType }
     * 
     */
    public InfoActividadEconomicaType createInfoActividadEconomicaType() {
        return new InfoActividadEconomicaType();
    }

    /**
     * Create an instance of {@link InfoIngresosType }
     * 
     */
    public InfoIngresosType createInfoIngresosType() {
        return new InfoIngresosType();
    }

    /**
     * Create an instance of {@link InfoFamiliarType }
     * 
     */
    public InfoFamiliarType createInfoFamiliarType() {
        return new InfoFamiliarType();
    }

    /**
     * Create an instance of {@link InfoSegSocialType }
     * 
     */
    public InfoSegSocialType createInfoSegSocialType() {
        return new InfoSegSocialType();
    }

    /**
     * Create an instance of {@link NombreCompletoType }
     * 
     */
    public NombreCompletoType createNombreCompletoType() {
        return new NombreCompletoType();
    }

    /**
     * Create an instance of {@link ProductoComunType }
     * 
     */
    public ProductoComunType createProductoComunType() {
        return new ProductoComunType();
    }

    /**
     * Create an instance of {@link IdentificacionType }
     * 
     */
    public IdentificacionType createIdentificacionType() {
        return new IdentificacionType();
    }

    /**
     * Create an instance of {@link ListaArchivosType }
     * 
     */
    public ListaArchivosType createListaArchivosType() {
        return new ListaArchivosType();
    }

    /**
     * Create an instance of {@link ArchivoType }
     * 
     */
    public ArchivoType createArchivoType() {
        return new ArchivoType();
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link AutenticarClienteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "autenticarClienteRequest")
    public JAXBElement<AutenticarClienteRequestType> createAutenticarClienteRequest(
            AutenticarClienteRequestType value) {
        return new JAXBElement<>(_AutenticarClienteRequest_QNAME, AutenticarClienteRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link AutenticarClienteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "autenticarClienteResponse")
    public JAXBElement<AutenticarClienteResponseType> createAutenticarClienteResponse(
            AutenticarClienteResponseType value) {
        return new JAXBElement<>(_AutenticarClienteResponse_QNAME, AutenticarClienteResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link CambiarClaveRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "cambiarClaveRequest")
    public JAXBElement<CambiarClaveRequestType> createCambiarClaveRequest(CambiarClaveRequestType value) {
        return new JAXBElement<>(_CambiarClaveRequest_QNAME, CambiarClaveRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link CambiarClaveResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "cambiarClaveResponse")
    public JAXBElement<CambiarClaveResponseType> createCambiarClaveResponse(CambiarClaveResponseType value) {
        return new JAXBElement<>(_CambiarClaveResponse_QNAME, CambiarClaveResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarComprobantePagoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarComprobantePagoRequest")
    public JAXBElement<ConsultarComprobantePagoRequestType> createConsultarComprobantePagoRequest(
            ConsultarComprobantePagoRequestType value) {
        return new JAXBElement<>(_ConsultarComprobantePagoRequest_QNAME, ConsultarComprobantePagoRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarComprobantePagoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarComprobantePagoResponse")
    public JAXBElement<ConsultarComprobantePagoResponseType> createConsultarComprobantePagoResponse(
            ConsultarComprobantePagoResponseType value) {
        return new JAXBElement<>(_ConsultarComprobantePagoResponse_QNAME, ConsultarComprobantePagoResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link HabilitarDebitoAutomaticoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "habilitarDebitoAutomaticoRequest")
    public JAXBElement<HabilitarDebitoAutomaticoRequestType> createHabilitarDebitoAutomaticoRequest(
            HabilitarDebitoAutomaticoRequestType value) {
        return new JAXBElement<>(_HabilitarDebitoAutomaticoRequest_QNAME, HabilitarDebitoAutomaticoRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link HabilitarDebitoAutomaticoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "habilitarDebitoAutomaticoResponse")
    public JAXBElement<HabilitarDebitoAutomaticoResponseType> createHabilitarDebitoAutomaticoResponse(
            HabilitarDebitoAutomaticoResponseType value) {
        return new JAXBElement<>(_HabilitarDebitoAutomaticoResponse_QNAME, HabilitarDebitoAutomaticoResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarHistoricoPagosRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarHistoricoPagosRequest")
    public JAXBElement<ConsultarHistoricoPagosRequestType> createConsultarHistoricoPagosRequest(
            ConsultarHistoricoPagosRequestType value) {
        return new JAXBElement<>(_ConsultarHistoricoPagosRequest_QNAME, ConsultarHistoricoPagosRequestType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarHistoricoPagosResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarHistoricoPagosResponse")
    public JAXBElement<ConsultarHistoricoPagosResponseType> createConsultarHistoricoPagosResponse(
            ConsultarHistoricoPagosResponseType value) {
        return new JAXBElement<>(_ConsultarHistoricoPagosResponse_QNAME, ConsultarHistoricoPagosResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link AceptarCreditoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "aceptarCreditoRequest")
    public JAXBElement<AceptarCreditoRequestType> createAceptarCreditoRequest(AceptarCreditoRequestType value) {
        return new JAXBElement<>(_AceptarCreditoRequest_QNAME, AceptarCreditoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link AceptarCreditoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "aceptarCreditoResponse")
    public JAXBElement<AceptarCreditoResponseType> createAceptarCreditoResponse(AceptarCreditoResponseType value) {
        return new JAXBElement<>(_AceptarCreditoResponse_QNAME, AceptarCreditoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarEstadoCreditoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarEstadoCreditoRequest")
    public JAXBElement<ConsultarEstadoCreditoRequestType> createConsultarEstadoCreditoRequest(
            ConsultarEstadoCreditoRequestType value) {
        return new JAXBElement<>(_ConsultarEstadoCreditoRequest_QNAME, ConsultarEstadoCreditoRequestType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarEstadoCreditoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarEstadoCreditoResponse")
    public JAXBElement<ConsultarEstadoCreditoResponseType> createConsultarEstadoCreditoResponse(
            ConsultarEstadoCreditoResponseType value) {
        return new JAXBElement<>(_ConsultarEstadoCreditoResponse_QNAME, ConsultarEstadoCreditoResponseType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarEstadoSolicitudRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarEstadoSolicitudRequest")
    public JAXBElement<ConsultarEstadoSolicitudRequestType> createConsultarEstadoSolicitudRequest(
            ConsultarEstadoSolicitudRequestType value) {
        return new JAXBElement<>(_ConsultarEstadoSolicitudRequest_QNAME, ConsultarEstadoSolicitudRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarEstadoSolicitudResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarEstadoSolicitudResponse")
    public JAXBElement<ConsultarEstadoSolicitudResponseType> createConsultarEstadoSolicitudResponse(
            ConsultarEstadoSolicitudResponseType value) {
        return new JAXBElement<>(_ConsultarEstadoSolicitudResponse_QNAME, ConsultarEstadoSolicitudResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link SolicitudCreditoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "solicitarCreditoRequest")
    public JAXBElement<SolicitudCreditoRequestType> createSolicitarCreditoRequest(SolicitudCreditoRequestType value) {
        return new JAXBElement<>(_SolicitarCreditoRequest_QNAME, SolicitudCreditoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link SolicitudCreditoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "solicitarCreditoResponse")
    public JAXBElement<SolicitudCreditoResponseType> createSolicitarCreditoResponse(
            SolicitudCreditoResponseType value) {
        return new JAXBElement<>(_SolicitarCreditoResponse_QNAME, SolicitudCreditoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link PagarCreditoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "pagarCreditoResponse")
    public JAXBElement<PagarCreditoResponseType> createPagarCreditoResponse(PagarCreditoResponseType value) {
        return new JAXBElement<>(_PagarCreditoResponse_QNAME, PagarCreditoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link PagarCreditoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "pagarCreditoRequest")
    public JAXBElement<PagarCreditoRequestType> createPagarCreditoRequest(PagarCreditoRequestType value) {
        return new JAXBElement<>(_PagarCreditoRequest_QNAME, PagarCreditoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link CalificarPromotorRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "calificarPromotorRequest")
    public JAXBElement<CalificarPromotorRequestType> createCalificarPromotorRequest(
            CalificarPromotorRequestType value) {
        return new JAXBElement<>(_CalificarPromotorRequest_QNAME, CalificarPromotorRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link CalificarPromotorResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "calificarPromotorResponse")
    public JAXBElement<CalificarPromotorResponseType> createCalificarPromotorResponse(
            CalificarPromotorResponseType value) {
        return new JAXBElement<>(_CalificarPromotorResponse_QNAME, CalificarPromotorResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarPromotorRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarPromotorRequest")
    public JAXBElement<ConsultarPromotorRequestType> createConsultarPromotorRequest(
            ConsultarPromotorRequestType value) {
        return new JAXBElement<>(_ConsultarPromotorRequest_QNAME, ConsultarPromotorRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarPromotorResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarPromotorResponse")
    public JAXBElement<ConsultarPromotorResponseType> createConsultarPromotorResponse(
            ConsultarPromotorResponseType value) {
        return new JAXBElement<>(_ConsultarPromotorResponse_QNAME, ConsultarPromotorResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RescateRequestType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "rescateRequest")
    public JAXBElement<RescateRequestType> createRescateRequest(RescateRequestType value) {
        return new JAXBElement<>(_RescateRequest_QNAME, RescateRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link RealizarRescateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "realizarRescateResponse")
    public JAXBElement<RealizarRescateResponseType> createRealizarRescateResponse(RealizarRescateResponseType value) {
        return new JAXBElement<>(_RealizarRescateResponse_QNAME, RealizarRescateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link SolicitarRescateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "solicitarRescateResponse")
    public JAXBElement<SolicitarRescateResponseType> createSolicitarRescateResponse(
            SolicitarRescateResponseType value) {
        return new JAXBElement<>(_SolicitarRescateResponse_QNAME, SolicitarRescateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link UltimosMovimientosRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "ultimosMovimientosRequest")
    public JAXBElement<UltimosMovimientosRequestType> createUltimosMovimientosRequest(
            UltimosMovimientosRequestType value) {
        return new JAXBElement<>(_UltimosMovimientosRequest_QNAME, UltimosMovimientosRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link UltimosMovimientosResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "ultimosMovimientosResponse")
    public JAXBElement<UltimosMovimientosResponseType> createUltimosMovimientosResponse(
            UltimosMovimientosResponseType value) {
        return new JAXBElement<>(_UltimosMovimientosResponse_QNAME, UltimosMovimientosResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarMovimientosAlcanciaRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarMovimientosAlcanciaRequest")
    public JAXBElement<ConsultarMovimientosAlcanciaRequestType> createConsultarMovimientosAlcanciaRequest(
            ConsultarMovimientosAlcanciaRequestType value) {
        return new JAXBElement<>(_ConsultarMovimientosAlcanciaRequest_QNAME,
                ConsultarMovimientosAlcanciaRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarMovimientosAlcanciaResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarMovimientosAlcanciaResponse")
    public JAXBElement<ConsultarMovimientosAlcanciaResponseType> createConsultarMovimientosAlcanciaResponse(
            ConsultarMovimientosAlcanciaResponseType value) {
        return new JAXBElement<>(_ConsultarMovimientosAlcanciaResponse_QNAME,
                ConsultarMovimientosAlcanciaResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarProductosClienteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarProductosClienteRequest")
    public JAXBElement<ConsultarProductosClienteRequestType> createConsultarProductosClienteRequest(
            ConsultarProductosClienteRequestType value) {
        return new JAXBElement<>(_ConsultarProductosClienteRequest_QNAME, ConsultarProductosClienteRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarProductosClienteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarProductosClienteResponse")
    public JAXBElement<ConsultarProductosClienteResponseType> createConsultarProductosClienteResponse(
            ConsultarProductosClienteResponseType value) {
        return new JAXBElement<>(_ConsultarProductosClienteResponse_QNAME, ConsultarProductosClienteResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link RegistroClienteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "registrarClienteRequest")
    public JAXBElement<RegistroClienteRequestType> createRegistrarClienteRequest(RegistroClienteRequestType value) {
        return new JAXBElement<>(_RegistrarClienteRequest_QNAME, RegistroClienteRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link RegistroClienteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "registrarClienteResponse")
    public JAXBElement<RegistroClienteResponseType> createRegistrarClienteResponse(RegistroClienteResponseType value) {
        return new JAXBElement<>(_RegistrarClienteResponse_QNAME, RegistroClienteResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ActualizarRegistroClienteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "actualizarRegistroClienteRequest")
    public JAXBElement<ActualizarRegistroClienteRequestType> createActualizarRegistroClienteRequest(
            ActualizarRegistroClienteRequestType value) {
        return new JAXBElement<>(_ActualizarRegistroClienteRequest_QNAME, ActualizarRegistroClienteRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ActualizarRegistroClienteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "actualizarRegistroClienteResponse")
    public JAXBElement<ActualizarRegistroClienteResponseType> createActualizarRegistroClienteResponse(
            ActualizarRegistroClienteResponseType value) {
        return new JAXBElement<>(_ActualizarRegistroClienteResponse_QNAME, ActualizarRegistroClienteResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link FinalizarRegistroClienteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "finalizarRegistroClienteRequest")
    public JAXBElement<FinalizarRegistroClienteRequestType> createFinalizarRegistroClienteRequest(
            FinalizarRegistroClienteRequestType value) {
        return new JAXBElement<>(_FinalizarRegistroClienteRequest_QNAME, FinalizarRegistroClienteRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link FinalizarRegistroClienteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "finalizarRegistroClienteResponse")
    public JAXBElement<FinalizarRegistroClienteResponseType> createFinalizarRegistroClienteResponse(
            FinalizarRegistroClienteResponseType value) {
        return new JAXBElement<>(_FinalizarRegistroClienteResponse_QNAME, FinalizarRegistroClienteResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarRetirosDisponiblesRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarRetirosDisponiblesRequest")
    public JAXBElement<ConsultarRetirosDisponiblesRequestType> createConsultarRetirosDisponiblesRequest(
            ConsultarRetirosDisponiblesRequestType value) {
        return new JAXBElement<>(_ConsultarRetirosDisponiblesRequest_QNAME,
                ConsultarRetirosDisponiblesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ConsultarRetirosDisponiblesResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "consultarRetirosDisponiblesResponse")
    public JAXBElement<ConsultarRetirosDisponiblesResponseType> createConsultarRetirosDisponiblesResponse(
            ConsultarRetirosDisponiblesResponseType value) {
        return new JAXBElement<>(_ConsultarRetirosDisponiblesResponse_QNAME,
                ConsultarRetirosDisponiblesResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ValidacionesVariasRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "validacionesVariasRequest")
    public JAXBElement<ValidacionesVariasRequestType> createValidacionesVariasRequest(
            ValidacionesVariasRequestType value) {
        return new JAXBElement<>(_ValidacionesVariasRequest_QNAME, ValidacionesVariasRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ValidacionesVariasResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "validacionesVariasResponse")
    public JAXBElement<ValidacionesVariasResponseType> createValidacionesVariasResponse(
            ValidacionesVariasResponseType value) {
        return new JAXBElement<>(_ValidacionesVariasResponse_QNAME, ValidacionesVariasResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ValidarAlcanciaRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "validarAlcanciaRequest")
    public JAXBElement<ValidarAlcanciaRequestType> createValidarAlcanciaRequest(ValidarAlcanciaRequestType value) {
        return new JAXBElement<>(_ValidarAlcanciaRequest_QNAME, ValidarAlcanciaRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ValidarAlcanciaResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "validarAlcanciaResponse")
    public JAXBElement<ValidarAlcanciaResponseType> createValidarAlcanciaResponse(ValidarAlcanciaResponseType value) {
        return new JAXBElement<>(_ValidarAlcanciaResponse_QNAME, ValidarAlcanciaResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ActualizarImagenesRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "actualizarImagenesRequest")
    public JAXBElement<ActualizarImagenesRequestType> createActualizarImagenesRequest(
            ActualizarImagenesRequestType value) {
        return new JAXBElement<>(_ActualizarImagenesRequest_QNAME, ActualizarImagenesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ActualizarImagenesResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "actualizarImagenesResponse")
    public JAXBElement<ActualizarImagenesResponseType> createActualizarImagenesResponse(
            ActualizarImagenesResponseType value) {
        return new JAXBElement<>(_ActualizarImagenesResponse_QNAME, ActualizarImagenesResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link FinSolicitudCreditoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "finSolicitudCreditoRequest")
    public JAXBElement<FinSolicitudCreditoRequestType> createFinSolicitudCreditoRequest(
            FinSolicitudCreditoRequestType value) {
        return new JAXBElement<>(_FinSolicitudCreditoRequest_QNAME, FinSolicitudCreditoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link FinSolicitudCreditoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "finSolicitudCreditoResponse")
    public JAXBElement<FinSolicitudCreditoResponseType> createFinSolicitudCreditoResponse(
            FinSolicitudCreditoResponseType value) {
        return new JAXBElement<>(_FinSolicitudCreditoResponse_QNAME, FinSolicitudCreditoResponseType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ActualizarImagenesClienteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "actualizarImagenesClienteRequest")
    public JAXBElement<ActualizarImagenesClienteRequestType> createActualizarImagenesClienteRequest(
            ActualizarImagenesClienteRequestType value) {
        return new JAXBElement<>(_ActualizarImagenesClienteRequest_QNAME, ActualizarImagenesClienteRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link ActualizarImagenesClienteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_SAM_CLIENTE, name = "actualizarImagenesClienteResponse")
    public JAXBElement<ActualizarImagenesClienteResponseType> createActualizarImagenesClienteResponse(
            ActualizarImagenesClienteResponseType value) {
        return new JAXBElement<>(_ActualizarImagenesClienteResponse_QNAME, ActualizarImagenesClienteResponseType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CabeceraSalida
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_CABECERA, name = "cabeceraSalida")
    public JAXBElement<CabeceraSalida> createCabeceraSalida(CabeceraSalida value) {
        return new JAXBElement<>(_CabeceraSalida_QNAME, CabeceraSalida.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CabeceraEntrada
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_CABECERA, name = "cabeceraEntrada")
    public JAXBElement<CabeceraEntrada> createCabeceraEntrada(CabeceraEntrada value) {
        return new JAXBElement<>(_CabeceraEntrada_QNAME, CabeceraEntrada.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link CabeceraRespuestaMultiple }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_CABECERA, name = "cabeceraRespuestaMultiple")
    public JAXBElement<CabeceraRespuestaMultiple> createCabeceraRespuestaMultiple(CabeceraRespuestaMultiple value) {
        return new JAXBElement<>(_CabeceraRespuestaMultiple_QNAME, CabeceraRespuestaMultiple.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoPersonaType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoPersona")
    public JAXBElement<InfoPersonaType> createInfoPersona(InfoPersonaType value) {
        return new JAXBElement<>(_InfoPersona_QNAME, InfoPersonaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoUbicacionType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoUbicacion")
    public JAXBElement<InfoUbicacionType> createInfoUbicacion(InfoUbicacionType value) {
        return new JAXBElement<>(_InfoUbicacion_QNAME, InfoUbicacionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoPersonalType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoPersonal")
    public JAXBElement<InfoPersonalType> createInfoPersonal(InfoPersonalType value) {
        return new JAXBElement<>(_InfoPersonal_QNAME, InfoPersonalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoConyugeType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoConyuge")
    public JAXBElement<InfoConyugeType> createInfoConyuge(InfoConyugeType value) {
        return new JAXBElement<>(_InfoConyuge_QNAME, InfoConyugeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link InfoActividadEconomicaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoActividadEconomica")
    public JAXBElement<InfoActividadEconomicaType> createInfoActividadEconomica(InfoActividadEconomicaType value) {
        return new JAXBElement<>(_InfoActividadEconomica_QNAME, InfoActividadEconomicaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoIngresosType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoIngresos")
    public JAXBElement<InfoIngresosType> createInfoIngresos(InfoIngresosType value) {
        return new JAXBElement<>(_InfoIngresos_QNAME, InfoIngresosType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoFamiliarType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoFamiliar")
    public JAXBElement<InfoFamiliarType> createInfoFamiliar(InfoFamiliarType value) {
        return new JAXBElement<>(_InfoFamiliar_QNAME, InfoFamiliarType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoSegSocialType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "infoSegSocial")
    public JAXBElement<InfoSegSocialType> createInfoSegSocial(InfoSegSocialType value) {
        return new JAXBElement<>(_InfoSegSocial_QNAME, InfoSegSocialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NombreCompletoType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "nombreCompleto")
    public JAXBElement<NombreCompletoType> createNombreCompleto(NombreCompletoType value) {
        return new JAXBElement<>(_NombreCompleto_QNAME, NombreCompletoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductoComunType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = QNAME_INFO_PERSONA, name = "productoComun")
    public JAXBElement<ProductoComunType> createProductoComun(ProductoComunType value) {
        return new JAXBElement<>(_ProductoComun_QNAME, ProductoComunType.class, null, value);
    }

}
