//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.bancocajasocial.com/co/schemas/sam/cliente/servicioSAMCliente/v1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.bcs.backend.services.client.sam; 
