//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 12:34:30 PM COT 
//


package co.com.bcs.backend.services.client.sam; 
 import lombok.NoArgsConstructor; 

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for ValidaDocumentosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidaDocumentosType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cedulaFrente" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cedulaAtras" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="selfie" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidaDocumentosType", propOrder = {
    "cedulaFrente",
    "cedulaAtras",
    "selfie"
})
@Getter
@Setter
@NoArgsConstructor 
 public class ValidaDocumentosType {

    @XmlElement(required = true)
    protected String cedulaFrente;
    @XmlElement(required = true)
    protected String cedulaAtras;
    @XmlElement(required = true)
    protected String selfie;
}
