//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.09 at 04:29:13 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.bancocajasocial.com/co/comunes/schema/Cabeceras/V1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.bcs.backend.services.client.encriptacion;
