CREATE TABLE API_BCS_LOG (
    NOMBRE_ALIADO VARCHAR2(100 CHAR) NOT NULL,
	NUMERO_ID VARCHAR2(100) ,
	NUMERO_REFERENCIA VARCHAR2(100) ,
	TIPO_ID VARCHAR2(100) ,
    FECHA TIMESTAMP NOT NULL,
	ORIGEN VARCHAR2(100) NOT NULL,
	METODO VARCHAR2(200) NOT NULL, 
	ESTADO VARCHAR2(10), 
	MENSAJE_ERROR CLOB,
	REQUEST CLOB,
	RESPONSE CLOB,
	CONSTRAINT API_BCS_LOG_PK PRIMARY KEY (ID));
	
CREATE TABLE API_BCS_ALIADO (
    NOMBRE_ALIADO VARCHAR2(400) NOT NULL,
	NIT_ALIADO VARCHAR2(500) NOT NULL,
	PUNTO_SERVICIO VARCHAR2(100) NOT NULL,
	CODIGO_SITIO VARCHAR2(100) NOT NULL,
	CODIGO_CORRESPONSAL VARCHAR2(100) NOT NULL,
	CODIGO_TERMINAL VARCHAR2(100) NOT NULL,
	GRUPO VARCHAR2(100),
	CONSTRAINT API_BCS_ALIADO_PK PRIMARY KEY (NOMBRE_ALIADO));
	