//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.09 at 11:22:20 AM COT 
//


package co.com.bcs.backend.services.client.samotc; 
 import lombok.NoArgsConstructor; 

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for CabeceraEntrada complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CabeceraEntrada"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="seguridad" type="{http://xmlns.bancocajasocial.com/co/comunes/schema/Cabeceras/V1.0}Seguridad" minOccurs="0"/&gt;
 *         &lt;element name="invocador" type="{http://xmlns.bancocajasocial.com/co/comunes/schema/Cabeceras/V1.0}Invocador" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CabeceraEntrada", namespace = "http://xmlns.bancocajasocial.com/co/comunes/schema/Cabeceras/V1.0", propOrder = {
    "seguridad",
    "invocador"
})
@Getter
@Setter
@NoArgsConstructor 
 public class CabeceraEntrada {

    protected Seguridad seguridad;
    protected Invocador invocador;
}
